# Generated by Django 5.1.6 on 2025-03-23 14:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', '4-Wheel Drive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Engine Size (L)'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_imported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='number_of_owners',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Power (HP)'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='steering',
            field=models.CharField(choices=[('right', 'Right-Hand Drive'), ('left', 'Left-Hand Drive')], default='right', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.PositiveIntegerField(verbose_name='Mileage in Km'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_auto', 'Semi-Automatic')], max_length=20),
        ),
    ]
