# Generated by Django 5.2.3 on 2025-06-29 14:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the car (e.g., Red, Blue, Black)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Overall condition of the vehicle', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the car was listed'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(help_text="Detailed description of the car's features, condition, and any additional information"),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of doors (2, 3, 4, or 5)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', '4-Wheel Drive')], help_text='Type of drive (FWD, RWD, AWD, or 4WD)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Engine displacement (e.g., 2.0L, 1.8L)', max_digits=4, null=True, verbose_name='Engine Size (L)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], default='petrol', help_text='Type of fuel the car uses', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_warranty',
            field=models.BooleanField(default=False, help_text='Check if the car comes with a warranty'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to feature this car on the homepage'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_imported',
            field=models.BooleanField(default=True, help_text='Check if the car is imported'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_negotiable',
            field=models.BooleanField(default=True, help_text='Check if the price is negotiable'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Mark as sold when the car is no longer available'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, help_text='Where the car is located for viewing/pickup', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, help_text='Car manufacturer (e.g., Toyota, Honda, BMW)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.PositiveIntegerField(help_text='Current mileage/kilometers on the odometer', verbose_name='Mileage in Km'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, help_text='Car model name (e.g., Camry, Accord, X5)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='number_of_owners',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of previous owners of the car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.PositiveIntegerField(blank=True, help_text='Engine power output (HP or kW)', null=True, verbose_name='Power (HP)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Asking price in your local currency', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of seats (2, 4, or 5)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering',
            field=models.CharField(choices=[('right', 'Right-Hand Drive'), ('left', 'Left-Hand Drive')], default='right', help_text='Steering position (Right-Hand Drive or Left-Hand Drive)', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(help_text='Enter a descriptive title for the car listing (e.g., "2020 Toyota Camry - Low Mileage")', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_auto', 'Semi-Automatic')], default='automatic', help_text='Transmission type (Manual/Automatic)', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the car was manufactured', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload car images', upload_to='cars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
