# Generated by Django 5.2.3 on 2025-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_image_alter_car_color_alter_car_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=100)),
                ('code', models.CharField(help_text='Country code (e.g., JP)', max_length=10)),
                ('flag_image', models.CharField(default='', help_text='Flag image code', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country Stock',
                'verbose_name_plural': 'Country Stocks',
            },
        ),
    ]
